from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
import json

from project_platform.core import GraphPlatform


def index(request):
    """Main page"""
    return render(request, 'index.html', {'message': 'Radi. Ovo je samo test prikaz.'})


def graph_data(request):
    """
    Returns the current graph from the platform as JSON.
    """
    platform = GraphPlatform()
    graph = platform.current_graph

    if graph is None:
        return JsonResponse({'nodes': {}, 'edges': [], 'directed': True})

    data = {
        'directed': graph.directed,
        'nodes': {
            node_id: {
                'id': node.id,
                'attributes': node.attributes,
            }
            for node_id, node in graph.nodes.items()
        },
        'edges': [
            {
                'id': edge.id,
                'source': edge.source,
                'target': edge.target,
                'attributes': edge.attributes,
            }
            for edge in graph.edges.values()
        ],
    }

    return JsonResponse(data)


def list_plugins(request):
    # getting all plugin names from the GraphPlatform
    data_source_plugins = GraphPlatform().get_data_source_plugins()
    visualizer_plugins = GraphPlatform().get_visualizer_plugins()
    # safe=False allows us to return a list instead of a dict
    response = {
        'data_source_plugins': data_source_plugins,
        'visualizer_plugins': visualizer_plugins,
    }
    return JsonResponse(response)


def get_data_plugin_parameters(request, plugin_name):
    """
    API endpoint koji vraća parametre za dati plugin.
    GET /api/plugins/<plugin_name>/parameters/
    """
    platform = GraphPlatform()
    try:
        parameters = platform.get_data_source_plugin_parameters(plugin_name)
        return JsonResponse(parameters, safe=False)
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def load_graph(request):
    try:
        data = json.loads(request.body)

        data_source = data.get('plugin')
        visualizer = data.get('visualizer')
        parameters = data.get('parameters', {})

        platform = GraphPlatform()

        graph = platform.load_graph(
            data_source_plugin_name=data_source,
            visualizer_plugin_name=visualizer,
            **parameters
        )

        node_count = len(graph.nodes) if graph and hasattr(
            graph, 'nodes') else 0
        edge_count = len(graph.edges) if graph and hasattr(
            graph, 'edges') else 0

        return JsonResponse({
            'status': 'success',
            'message': f'Graph loaded with {data_source}',
            'visualizer': visualizer,
            'node_count': node_count,
            'edge_count': edge_count,
            'graph': graph.to_json() if graph else None,
            'visualizer_assets': platform.get_current_visualizer_assets(),
            'workspaces': platform.list_workspaces(),
            'workspace': platform.get_active_workspace_payload()['workspace'],
            'operations': [],
        })

    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


def list_visualizers(request):
    platform = GraphPlatform()
    visualizers = platform.get_visualizer_plugins()
    return JsonResponse(visualizers, safe=False)


def render_graph(request):
    """
    Renders the current graph using the current visualizer plugin.
    Returns the HTML generated by the visualizer.
    """
    platform = GraphPlatform()

    try:
        html = platform.render_current_graph()
        response = HttpResponse(html)
        response['X-Frame-Options'] = 'SAMEORIGIN'
        return response
    except Exception as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(f'<html><body><h1>Error rendering graph</h1><pre>{str(e)}</pre></body></html>', status=500)


def visualizer_assets(request):
    """Returns HTML and CSS generated by the selected visualizer plugin."""
    platform = GraphPlatform()
    try:
        visualizer = request.GET.get('visualizer')
        return JsonResponse(platform.get_current_visualizer_assets(visualizer))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def apply_graph_operations(request):
    """Apply search/filter operations in the platform and return the resulting subgraph."""
    try:
        data = json.loads(request.body or '{}')
        operations = data.get('operations', [])
        result = GraphPlatform().apply_operations(operations)
        return JsonResponse({
            'status': 'success',
            **result,
        })
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=400)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)



@csrf_exempt
@require_http_methods(["POST"])
def execute_cli_command(request):
    """Execute a CLI command against the current graph."""
    try:
        data = json.loads(request.body or '{}')
        command = data.get('command', '')
        result = GraphPlatform().execute_cli_command(command)
        return JsonResponse(result)
    except ValueError as e:
        return JsonResponse({'status': 'error', 'error': str(e)}, status=400)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'status': 'error', 'error': str(e)}, status=500)



def list_workspaces(request):
    platform = GraphPlatform()
    return JsonResponse({
        'active_workspace_id': platform.active_workspace_id,
        **platform.get_active_workspace_payload(),
    })


@csrf_exempt
@require_http_methods(["POST"])
def create_workspace(request):
    try:
        data = json.loads(request.body or '{}')
        payload = GraphPlatform().create_workspace(data.get('name', 'New Workspace'))
        return JsonResponse({'status': 'success', **payload})
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def save_workspace(request):
    try:
        data = json.loads(request.body or '{}')
        payload = GraphPlatform().save_workspace(
            workspace_id=data.get('workspace_id'),
            name=data.get('name')
        )
        return JsonResponse({'status': 'success', **payload})
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=400)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def switch_workspace(request):
    try:
        data = json.loads(request.body or '{}')
        payload = GraphPlatform().switch_workspace(data.get('workspace_id'))
        return JsonResponse({'status': 'success', **payload})
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=404)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
def delete_workspace(request):
    try:
        data = json.loads(request.body or '{}')
        payload = GraphPlatform().delete_workspace(data.get('workspace_id'))
        return JsonResponse({'status': 'success', **payload})
    except ValueError as e:
        return JsonResponse({'error': str(e)}, status=400)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return JsonResponse({'error': str(e)}, status=500)
